[[redirects]]
  from = "/serve_rev/*/inspector.html"
  to = "/inspector.html"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/serve_rev/@*/devtools.manifest"
  to = "https://chrome-devtools-frontend.appspot.com/serve_rev/@:splat/:splat.manifest"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/serve_rev/*"
  to = "https://chrome-devtools-frontend.appspot.com/serve_rev/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/serve_file/*/inspector.html"
  to = "/inspector.html"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/serve_file/@*/devtools.manifest"
  to = "https://chrome-devtools-frontend.appspot.com/serve_file/@:splat/:splat.manifest"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/serve_file/*"
  to = "https://chrome-devtools-frontend.appspot.com/serve_file/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
