[[redirects]]
  from = "/*/inspector.html"
  to = "/inspector.html"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/*"
  to = "https://chrome-devtools-frontend.appspot.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect